LINE_WIDTH = 45
print('=' * LINE_WIDTH)
print('БУХГАЛТЕРСКИЙ КАЛЬКУЛЯТОР')
print('=' * LINE_WIDTH)
print()
print('1. Рассчитать НДФЛ (13%)')
print('2. Рассчитать страховые взносы (30%)')
print('3. Рассчитать сумму "грязными"')
print('4. Выход')
num = int(input('Выберите действие (1-4):'))